### ISSUE TITLE
Ignored Properties

### ISSUE THREAD

**Issue by NickNikitas** [confluentinc/cp-demo#10]
https://github.com/confluentinc/cp-demo/blob/05f2b7d5fa360b54c09430428940fc8feb37e8bb/docker-compose.yml#L91

When I run docker-compose up, the interceptor doesn't seem to be applied.
[2017-12-13 04:42:40,806] INFO ProducerConfig values: 
...
	interceptor.classes = null

**Comment by gwenshap** [comment]
Do you see data in "stream monitoring" view? If you do, then the interceptors apply anyway. If you don't... we can use more of the log to see what happened :)

**Comment by NickNikitas** [comment]
[interceptor.log](https://github.com/confluentinc/cp-demo/files/1556333/interceptor.log)
I attached the rest of the log.  (Note: When I change the property to CONNECT_INTERCEPTOR_CLASSES, it does attempt to load the interceptors.  (It blows up when trying to load the class for consumer interceptor, because it can't distinguish producer from consumer configs.)

**Comment by ybyzek** [comment]
I think the logging may be misleading. Even though it says

`interceptor.classes = null`

in fact the interceptors are probably still being applied.

To verify, please look at C3 "Stream Monitoring" and look for a consumer group corresponding to Elasticsearch (something similar to https://github.com/confluentinc/cp-demo/blob/master/images/connect_consumer_group.png)

**Comment by NickNikitas** [comment]
You are correct.  Thank you, I understand now.  I followed the tutorial and the logs do eventually show ``interceptor.classes = [io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor]`` when the tasks are initialized.
