### ISSUE TITLE
docker-compose fails on elasticsearch/kibana images

### ISSUE THREAD

**Issue by vinothchandar** [confluentinc/cp-demo#106]
Hit this when setting up afresh (i.e no prior docker images) and isolated it to the docker-compose command in the start script. Specifically, ES and Kibana versions seem to be problematic? 

```
$ docker-compose up -d
Pulling kibana (docker.elastic.co/kibana/kibana:5.5.2)...
5.5.2: Pulling from kibana/kibana
364f9b7c969a: Verifying Checksum
e49bda868a31: Download complete
19392fbddf76: Download complete
7a6a24f9cca6: Download complete
945295f0f086: Download complete
ad5548b19b09: Download complete
52c4777d1729: Download complete
670929eeaf05: Download complete
568cf9e954fe: Download complete
ERROR: filesystem layer verification failed for digest sha256:364f9b7c969aed6ff05b7ced04b1b53b824386288dffb1e6aec41d5a706dd51e
```

I bumped both their versions up and it seems to work. Is this a real issue?

**Comment by vinothchandar** [comment]
Another nit: 
>View the data in the Kibana dashboard at http://localhost:5601/app/kibana#/dashboard/Wikipedia
Could not login to the updated Kibana. So not sure if I am doing this right either.

**Comment by javabrett** [comment]
Image versions are now:

```
docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
docker.elastic.co/kibana/kibana-oss:7.10.0
```

... and these are pulling correctly, so closing this issue - thanks!
