### ISSUE TITLE
cp-demo - elasticsearch   bootstrap  checks failed 

### ISSUE THREAD

**Issue by pgibert** [confluentinc/cp-demo#11]
i got  this error  on my ubuntu vm  for elasticsearch_1  | ERROR: [1] bootstrap checks failed
and so ES and kibana were not  ok......

i resolved  by adding  1 line in docker-compose.yml ( elasticsearch/environment)
      discovery.type: "single-node"

now everything is ok at start ( checked by docker ps -a ) 

HTH 
phil

**Comment by ybyzek** [comment]
@pgibert : thanks for finding the problem and suggested solution!  It must be something unique to the environment, because we're not seeing that issue here.

Regardless, I committed a fix https://github.com/confluentinc/cp-demo/commit/7bf7ee8e7bace0a8bf544b632a997c0ce5cfb046
