### ISSUE TITLE
Bootstrap checks failed

### ISSUE THREAD

**Issue by DaveSlinn** [confluentinc/cp-demo#114]
My colleague and I are both walking through this demo setup. We are using Ubuntu 18.04 running on a Windows 10 VM.  We encountered two issues.

1. The mounting of the $PWD/scripts/security:/etc/kafka/secrets (line 28) for the zookeeper service in  docker-compose.yml was not working until I had added myself to the linux docker group using ``usermod -aG docker [username]``.  The container would continuously restart, and the docker logs showed repeated errors when it could not locate zookeeper_jaas.conf.

2. The elasticsearch service would start and then stop 30 seconds later. We traced that to the bootstrap checks elasticsearch does at startup.  It reported we only had 4096 file descriptors available and it required a minimum of over 200k.  I researched the issue on the[ elastic search documentation for this specific version](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html) and it describes adding an environment variable (discovery.type) to indicate running in development mode will bypass those bootstrap checks. Added the following:
```
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"     # <-- added this
```
and everything is working now.  I found #11 mentioned this before and it seems like that setting was added way back in [Dec 2017](https://github.com/confluentinc/cp-demo/commit/7bf7ee8e7bace0a8bf544b632a997c0ce5cfb046) but is no longer present. I'm not sure why - could have saved us a couple of hours.

**Comment by javabrett** [comment]
Issue 2 has since been fixed and that recommended config added.  Issue 1 - possibly Windows related??
