### ISSUE TITLE
connector problem  regarding irc  connector 

### ISSUE THREAD

**Issue by pgibert** [confluentinc/cp-demo#12]
hello, continuing the demo set up i got  a problem regarding  irc connector  ( when the ./scripts_ksql/submit_wikipedia_irc_config.sh is executed ..) 
the command **docker-compose  ps** is ok !
 and 
curl -X GET "http://localhost:8083/connectors"
result is :
**[]**
but when the script is run it  gives   error_code":500,  ' see below please 
curl -X POST -H "Content-Type: application/json" --data "{
  "name": "wikipedia-irc",
  "config": {
    "connector.class": "com.github.cjmatta.kafka.connect.irc.IrcSourceConnector",
    "transforms": "WikiEditTransformation",
    "transforms.WikiEditTransformation.type": "com.github.cjmatta.kafka.connect.transform.wikiedit.WikiEditTransformation",
    "transforms.wikiEditTransformation.save.unparseable.messages": true,
    "transforms.wikiEditTransformation.dead.letter.topic": "wikipedia.failed",
    "irc.channels": "#en.wikipedia,#fr.wikipedia,#es.wikipedia,#ru.wikipedia,#en.wiktionary,#de.wikipedia,#zh.wikipedia,#sd.wikipedia,#it.wikipedia,#mediawiki.wikipedia,#commons.wikimedia,#eu.wikipedia,#vo.wikipedia,#eo.wikipedia,#uk.wikipedia",
    "irc.server": "irc.wikimedia.org",
    "kafka.topic": "wikipedia.parsed",
    "producer.interceptor.classes": "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor",
    "tasks.max": "1"
  }
}" http://localhost:8083/connectors
**{"error_code":500,"message":"Failed to find any class that implements Connector** and which name matches com.github.cjmatta.kafka.connect.irc.IrcSourceConnector, available connectors are: PluginDesc{klass=class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector, name='io.confluent.connect.elasticsearch.ElasticsearchSinkConnector', version='3.3.0', encodedVersion=3.3.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class io.confluent.connect.hdfs.HdfsSinkConnector, name='io.confluent.connect.hdfs.HdfsSinkConnector', version='3.3.0', encodedVersion=3.3.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class io.confluent.connect.hdfs.tools.SchemaSourceConnector, name='io.confluent.connect.hdfs.tools.SchemaSourceConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class io.confluent.connect.jdbc.JdbcSinkConnector, name='io.confluent.connect.jdbc.JdbcSinkConnector', version='3.3.0', encodedVersion=3.3.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class io.confluent.connect.jdbc.JdbcSourceConnector, name='io.confluent.connect.jdbc.JdbcSourceConnector', version='3.3.0', encodedVersion=3.3.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class io.confluent.connect.s3.S3SinkConnector, name='io.confluent.connect.s3.S3SinkConnector', version='3.3.0', encodedVersion=3.3.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class io.confluent.connect.storage.tools.SchemaSourceConnector, name='io.confluent.connect.storage.tools.SchemaSourceConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='0.11.0.0-cp1', encodedVersion=0.11.0.0-cp1, type=source, typeName='source', location='classpath'}"}

-----------------------
best regards 
phil

**Comment by ybyzek** [comment]
The error message indicates that `com.github.cjmatta.kafka.connect.irc.IrcSourceConnector` is not an available connector.

As a check, do you see `kafka-connect-irc` listed in the `connect-plugins` directory?

This connector is compiled as part of the step https://github.com/confluentinc/cp-demo#installation:

`$ make clean all
...
$ ls connect-plugins`

**Comment by pgibert** [comment]
hello yeah that's  my problem :-) 
the make clean all  run nicely and i checked that every thing was ok

pg$  **find connect-plugins/**
connect-plugins/
connect-plugins/kafka-connect-transform-nullfilter
connect-plugins/kafka-connect-transform-nullfilter/null-filter-4.0.0-SNAPSHOT.jar
connect-plugins/WikiEditTransformation-3.3.0.jar
connect-plugins/kafka-connect-irc
connect-plugins/kafka-connect-irc/irclib-1.10.jar
connect-plugins/kafka-connect-irc/kafka-connect-irc-3.3.0.jar
connect-plugins/kafka-connect-irc/guava-19.0.jar
pg$ pwd
/home/pg/cp-demo

From the docker log , i see the **connect_1** logs that are correct up to my curl POST regarding the irc connector  :-(

connect_1        | [2017-12-13 13:15:31,118] INFO 172.19.0.9 - - [13/Dec/2017:13:15:28 +0000] "GET /connectors HTTP/1.1" 200 2  2785 (org.apache.kafka.connect.runtime.rest.RestServer)
connect_1        | [2017-12-13 13:15:31,623] INFO 172.19.0.9 - - [13/Dec/2017:13:15:31 +0000] "GET /connector-plugins HTTP/1.1" 200 890  124 (org.apache.kafka.connect.runtime.rest.RestServer)
connect_1        | [2017-12-13 13:15:31,786] INFO 172.19.0.9 - - [13/Dec/2017:13:15:31 +0000] "GET /connectors HTTP/1.1" 200 2  4 (org.apache.kafka.connect.runtime.rest.RestServer)
connect_1        | [2017-12-13 13:44:54,328] INFO 172.19.0.1 - - [13/Dec/2017:13:44:54 +0000] "POST **/connectors HTTP/1.1" 500 3732  81 (org.apache.kafka.connect.runtime.rest.RestServer)**
connect_1        | [2017-12-13 13:45:30,007] INFO 172.19.0.1 - - [13/Dec/2017:13:45:29 +0000] "POST /connectors HTTP/1.1" 500 3732  8 (org.apache.kafka.connect.runtime.rest.RestServer)
connect_1        | [2017-12-13 13:45:30,250] INFO 172.19.0.1 - - [13/Dec/2017:13:45:30 +0000] "POST /connectors HTTP/1.1" 400 445  15 (org.apache.kafka.connect.runtime.rest.RestServer)
connect_1        | [2017-12-13 14:00:13,538] WARN  (org.eclipse.jetty.servlet.ServletHandler)
connect_1        | javax.servlet.ServletException: java.lang.NullPointerException
connect_1        |      at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
connect_1        |      at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)

strange is'nt it .. the docker for the  connector seems not founding  java classes for  irc ... ?

best R
philg

**Comment by ybyzek** [comment]
This can happen if you compiled the connectors after your brought up your Docker environment, but then did not restart Docker.

To correct this:

`docker-compose down`
`docker-compose up -d`

**Comment by pgibert** [comment]
hello after investigation :-)
i got this warn from the docker compose logs
**WARNING: The PWD variable is not set. Defaulting to a blank string** 
it strange because my PWDv ar is exported at the shell level  ...
and  i saw in the  compose yaml that is used for the connect /volumes ....
  - $PWD/connect-plugins:/connect-plugins


my HW/SW is ubuntu 14.04 on a VM

best regards

**Comment by ybyzek** [comment]
Good find!

I'm not sure why `$PWD` isn't picking up the environment variable if it is set in the shell. Some suggestions:

1. Edit `docker-compose.yml` and replace `$PWD` with `${PWD}`

2. Edit `docker-compose.yml` and replace `$PWD` with the exact path, thereby removing the dependency on the environment variable completely

3. Try any of the other documented options to set `PWD`: https://docs.docker.com/compose/environment-variables/

**Comment by pgibert** [comment]
Thanks fixed ... 
Last issue :-)
you should indicates that docker compose version required is 1.12.0+ 
for version 2.1  yml file and for the docker exec .......
best regards
phil

**Comment by ybyzek** [comment]
Added a version note to the README.
