### ISSUE TITLE
A clean maven repository fails

### ISSUE THREAD

**Issue by framiere** [confluentinc/cp-demo#2]
Hi, 

This demo is suited for new kafka/confluent users, and that's great ! Good job !

However new kafka/confluent users will have not have any confluent dependencies in their local maven cache. Thus they will not be able to access `connect-api-0.11.0.0-cp1.jar` as https://github.com/cjmatta/kafka-connect-transform-wikiedit did not defined the confluent repository.

I proposed https://github.com/cjmatta/kafka-connect-transform-wikiedit/pull/1 to fix that.

Meanwhile we can do a few things

- ping @cjmatta to accept the pull request :)
- specify in the `.gitmodules` to use the `3.3.0` branch as the repository is defined see https://github.com/cjmatta/kafka-connect-transform-wikiedit/blob/3.3.0/pom.xml#L28
-  download `connect-api-0.11.0.0-cp1.jar` in the makefile and install it manual via maven see https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
- apply the patch on kafka-connect-transform-wikiedit in the makefile

To reproduce the problem : 
```
$ echo faking empty maven repository
$ mv ~/.m2/repository ~/.m2/repository-temp
$ make clean all
...
[INFO] BUILD FAILURE
...
[ERROR] Failed to execute goal on project WikiEditTransformation: Could not resolve dependencies for project com.github.cjmatta.kafka.connect.transform.wikiedit:WikiEditTransformation:jar:3.3.0: Could not find artifact org.apache.kafka:connect-api:jar:0.11.0.0-cp1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
...
$ echo $?
2
$ echo setting back repository
$ rm -rf ~/.m2/repository && mv ~/.m2/repository-temp ~/.m2/repository
```

Cheers !

**Comment by ybyzek** [comment]
@framiere : Thanks for identifying this issue!

Update:
1. @cjmatta merged your PR
2. I have changed this repo to point to the updated submodule with [this PR](https://github.com/confluentinc/cp-demo/commit/8e8d446bcbd77cbeef8887a55cf09acc5ffbe269) 3. I verified that it works

Does this address the problem?

**Comment by framiere** [comment]
Yes, it does. Thanks !
