### ISSUE TITLE
tools token expire and there is no clear path on how to request a new one

### ISSUE THREAD

**Issue by jeqo** [confluentinc/cp-demo#203]
Following [demo docs](https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html) security and schema registry steps: 

if keeping the components alive for a while (haven't managed to test how long but probably an hour or so), then message is returned: 

```
docker-compose exec tools bash -c "confluent iam rolebinding create \
    --principal User:appSA \
    --role ResourceOwner \
    --resource Subject:users-value \
    --kafka-cluster-id $KAFKA_CLUSTER_ID \
    --schema-registry-cluster-id schema-registry"
Your token has expired. You are now logged out.
Error: You must log in to run that command.
```

Is there any guidance on how to request a new topic on the tools service?

**Comment by jeqo** [comment]
Only workaround I've found so far is to stop/start the whole demo which takes a while

**Comment by ybyzek** [comment]
@jeqo here's what the code does to refresh login: 

https://github.com/confluentinc/cp-demo/blob/5.4.1-post/scripts/validate/validate_rest_proxy.sh#L30

**Comment by jeqo** [comment]
thanks @ybyzek that works :) 

I have created #205 as an attempt to have this as part of the documentation. Hope it make sense.
