### ISSUE TITLE
running "./scripts/start.sh" fails

### ISSUE THREAD

**Issue by binygreenberg** [confluentinc/cp-demo#228]
```
Building custom Docker image with Connect version 5.5.0 and connector version 5.5.0
docker build --build-arg CP_VERSION=5.5.0 --build-arg CONNECTOR_VERSION=5.5.0 -t localbuild/connect:5.5.0-5.5.0 -f /Users/binyamingreenberg/my-workspace/cp-demo/scripts/../Dockerfile-confluenthub .
Sending build context to Docker daemon  115.7MB
Step 1/6 : ARG CP_VERSION
Step 2/6 : FROM confluentinc/cp-server-connect-base:$CP_VERSION
 ---> b70f0c2cba1b
Step 3/6 : ARG CONNECTOR_VERSION=5.4.1
 ---> Using cache
 ---> bc103f022980
Step 4/6 : ENV CONNECT_PLUGIN_PATH: "/usr/share/java,/connect-plugins,/usr/share/confluent-hub-components"
 ---> Using cache
 ---> 4f4c12a420f2
Step 5/6 : RUN confluent-hub install --no-prompt confluentinc/kafka-connect-replicator:${CONNECTOR_VERSION}
 ---> Using cache
 ---> f916f60c0621
Step 6/6 : RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:${CONNECTOR_VERSION}
 ---> Running in b27033e7fa97
OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
ERROR: Docker image build failed. Please troubleshoot and try again.
```

**Comment by ybyzek** [comment]
@binygreenberg I haven't encountered this error before.

Based on quick Googling, perhaps it is related to your environment. We validate on https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html?#run-demo .  In your environment, what are:

1. OS version
2. Docker version
3. Docker Compose version

**Comment by mjthompson2107** [comment]
I am also facing an issue with "./scripts/start.sh". Please could someone help me with this, as I have been experiencing issues in trying to run cp-demo for a few days now. I keep getting the following warnings whilst running this script, but not sure if these are significant and how I can solve these:

WARNING: The ZOOKEEPER_SSL_CIPHER_SUITES variable is not set. Defaulting to a blank string.
WARNING: The SSL_CIPHER_SUITES variable is not set. Defaulting to a blank string.
WARNING: The CONNECTOR_VERSION variable is not set. Defaulting to a blank string.
WARNING: The CONTROL_CENTER_KSQL_WIKIPEDIA_URL variable is not set. Defaulting to a blank string.
WARNING: The CONTROL_CENTER_KSQL_WIKIPEDIA_ADVERTISED_URL variable is not set. Defaulting to a blank string.

Ultimately, I get the error, "The logs in control-center container do not show 'Started NetworkTrafficServerConnector' after $MAX_WAIT seconds. Please troubleshoot with 'docker-compose ps' and 'docker-compose logs'.\n"". I am not sure how to solve this

My environment versions are:

1. OS Version - CentOS Linux 7 (Core)
2. Docker version 20.10.1, build 831ebea
3. docker-compose version 1.18.0, build 8dd22a9

**Comment by ybyzek** [comment]
@mjthompson2107 

1. Which branch of cp-demo are you using?  

2. Please use `6.0.1-post` branch and refresh the code:

```
git checkout 6.0.1-post
git fetch
git pull
```

**Comment by mjthompson2107** [comment]
Thanks that now works. I removed the clone and cloned again using the details you have provided. Not sure which version I was using before, but think it might have been this version and not sure what I had changed that caused it to not work

**Comment by javabrett** [comment]
This issue is stale and likely related to a problem with the local Docker daemon.  Please open a new issue if encountered again.
