### ISSUE TITLE
Incorrect docker-compose argument syntax

### ISSUE THREAD

**Issue by gollyg** [confluentinc/cp-demo#229]
https://github.com/confluentinc/cp-demo/blob/1e31f9177e3445b8f24930a70d46b12ca843c752/Dockerfile-confluenthub#L18

I am new here, but docker-compose syntax seems to require curly brackets?

**Comment by gollyg** [comment]
There are also potential issues with the variable being declared but not set within this file. Would this typically use the environmental variables file?

**Comment by javabrett** [comment]
@gollyg this looks ok to me - it's `Dockerfile` syntax so not `docker-compose` in this spot.  Is it causing an error or warning or other issues in your build - if so please post output.

Per https://docs.docker.com/engine/reference/builder/#environment-replacement braces/no should be equivalent except you can do more with whitespace and bash-style defaults/mandatory with the braces.  Maybe an argument can be made for changing.

**Comment by gollyg** [comment]
Okay. Thanks for that. An argument could be made for consistency within the file, but closing this PR
