### ISSUE TITLE
No such image: confluentinc/cp-zookeeper:: invalid reference format when running start.sh

### ISSUE THREAD

**Issue by ChauncyYinXun** [confluentinc/cp-demo#269]
Hi, I am running this cp-demo on windows 10 with Git Bash. I am seeing this error when running start.sh  

What could be the issue?
<img width="943" alt="zookeeper" src="https://user-images.githubusercontent.com/32704417/97404248-be7e3980-1930-11eb-84ed-8b2b46e7bc38.png">

My docker version is below: 
<img width="568" alt="docker_version" src="https://user-images.githubusercontent.com/32704417/97403996-5891b200-1930-11eb-9fa3-4892063bb846.png">

**Comment by ybyzek** [comment]
@ChauncyYinXun please see https://github.com/confluentinc/examples/issues/565#issuecomment-614649458 .  Can you substitute tag `6.0.0` instead of `CONFLUENT_DOCKER_TAG` and try again?

**Comment by ChauncyYinXun** [comment]
Hi, @ybyzek Per [confluentinc/examples#565 (comment)](https://github.com/confluentinc/examples/issues/565#issuecomment-614649458), I replaced .env file content with the content of ./env_files/config.env  

Here's a screenshot of my .env file
<img width="960" alt="env" src="https://user-images.githubusercontent.com/32704417/97601863-9df3d380-1a45-11eb-96c5-690d468f102b.png">

and I am getting the same error: 
<img width="940" alt="error" src="https://user-images.githubusercontent.com/32704417/97602019-c67bcd80-1a45-11eb-80ef-20791c9399ed.png">

Any advice to make it work on windows 10?

**Comment by ohmygaugh-crypto** [comment]
I'm facing the same config issue as those above have mentioned in the thread.

**Comment by kaijunxu** [comment]
@ChauncyYinXun - for cp-demo, it will be a little different from the issue linked by @ybyzek. Here is what I do to get it working on Win 10 (using Docker Desktop and WSL with Ubuntu 18.0.4 LTS):

- copy contents of /env_files/config.env to /scripts/.env
- edit [/scripts/helper/functions.sh](https://github.com/confluentinc/cp-demo/blob/6.0.0-post/scripts/helper/functions.sh): under function "build_connect_image()", change the symbolic "DOCKERFILE="${DIR}/../Dockerfile-confluenthub" to absolute e.g. "DOCKERFILE=$"/mnt/c/cp-demo-6.0.0-post/Dockerfile-confluenthub" - line 111, though you may also need to do that for line 109
- edit [Dockerfile-confluenthub](https://github.com/confluentinc/cp-demo/blob/6.0.0-post/Dockerfile-confluenthub) COPY (line 37) from "COPY /scripts/security/kafka.connect.truststore.jks /tmp/kafka.connect.truststore.jks" to "COPY security/kafka.connect.truststore.jks /tmp/kafka.connect.truststore.jks"
- IF your start.sh uses the Dockerfile-local, repeat last step for Dockerfile-local (line 38) - you will know which dockerfile is being used from the output.

**Comment by ChauncyYinXun** [comment]
> @ChauncyYinXun - for cp-demo, it will be a little different from the issue linked by @ybyzek. Here is what I do to get it working on Win 10 (using Docker Desktop and WSL with Ubuntu 18.0.4 LTS):
> 
> 1. copy contents of /env_files/config.env to /scripts/.env
> 2. edit [/scripts/helper/functions.sh](https://github.com/confluentinc/cp-demo/blob/6.0.0-post/scripts/helper/functions.sh): under function "build_connect_image()", change the symbolic "DOCKERFILE="${DIR}/../Dockerfile-confluenthub" to absolute e.g. "DOCKERFILE=$"/mnt/c/cp-demo-6.0.0-post/Dockerfile-confluenthub" - line 111, though you may also need to do that for line 109
> 
> Most of these are because Windows does not play well with the symbolic links that are used. Note that (2) may only work for WSL, you'll have to provide an absolute path that works for Git Bash.

**Comment by ChauncyYinXun** [comment]
> > @ChauncyYinXun - for cp-demo, it will be a little different from the issue linked by @ybyzek. Here is what I do to get it working on Win 10 (using Docker Desktop and WSL with Ubuntu 18.0.4 LTS):
> > 
> > 1. copy contents of /env_files/config.env to /scripts/.env
> > 2. edit [/scripts/helper/functions.sh](https://github.com/confluentinc/cp-demo/blob/6.0.0-post/scripts/helper/functions.sh): under function "build_connect_image()", change the symbolic "DOCKERFILE="${DIR}/../Dockerfile-confluenthub" to absolute e.g. "DOCKERFILE=$"/mnt/c/cp-demo-6.0.0-post/Dockerfile-confluenthub" - line 111, though you may also need to do that for line 109
> > 
> > Most of these are because Windows does not play well with the symbolic links that are used. Note that (2) may only work for WSL, you'll have to provide an absolute path that works for Git Bash.

@kaijunxu Thanks a lot for your reply. When I am setting up WSL with Ubuntu 18.0.4 LTS, I am getting the below error: 
![image](https://user-images.githubusercontent.com/32704417/101733451-de8d4500-3af9-11eb-827b-f6d0b4fa42d8.png)

![image](https://user-images.githubusercontent.com/32704417/101733537-0086c780-3afa-11eb-8848-28ffff5361ca.png)

![image](https://user-images.githubusercontent.com/32704417/101733688-30ce6600-3afa-11eb-90db-62733473bd7a.png)

I have used sed -i 's/\r//g' start.sh and had the same error
![image](https://user-images.githubusercontent.com/32704417/101735991-adaf0f00-3afd-11eb-815f-98d3b7cdd4b4.png)

And this is what I got after running start.sh using Git Bash: 

![image](https://user-images.githubusercontent.com/32704417/101737202-85281480-3aff-11eb-90a5-a31ab0ebf836.png)

![image](https://user-images.githubusercontent.com/32704417/101736517-7db43b80-3afe-11eb-9105-a1b22fd254c3.png)

![image](https://user-images.githubusercontent.com/32704417/101736396-49d91600-3afe-11eb-9117-1a9d24319eca.png)

**Comment by kaijunxu** [comment]
@ChauncyYinXun - for issues you saw when running in Git Bash i.e. the second half of your comment - this is due to my mistake earlier - you should copy contents of /env_files/config.env to /.env (and not /scripts/.env as I previously stated, though I personally do both since I don't want to troubleshoot which).

As for the first half of your comment, issues running in WSL - this looks like an EOL conversion issue - see for example [https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings](https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings). I personally use Notepad++ to ensure the script files have the right EOL format (Edit > EOL conversion > Unix (LF)). You'll want to check this at least for /scripts/start.sh, /scripts/stop.sh and /scripts/helper/functions.sh (and possibly for *.sh).

**Comment by krishnasingh3** [comment]
In my case, there is no script folder in clickstream.

**Comment by ybyzek** [comment]
My colleague just validated `cp-demo` works (from latest in branch `6.1.0-post`) with the following notes (which I wanted to document here in case others come across this GitHub issue)

--------------

OS
Edition: Windows 10 Enterprise
Version: 20H2
Installed on: ‎4/‎18/‎2020
OS build: 19042.844
Experience: Windows Feature Experience Pack 120.2212.551.0

Hardware
Dell XPS 15 9530
Processor Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz 2.30 GHz
Installed RAM 16.0 GB
Product ID 00329-10280-00000-AA963
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points

Docker v19
$ docker --version
Docker version 19.03.13, build 4484c46

Ubuntu v20.10
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.10
Release: 20.10
Codename: groovy

WSL 2 kernel 4.19
$ uname -a
Linux Adira 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> It’s worth noting that Docker on Windows no longer has a config for setting the memory size of the VM, because WSL 2 doesn't run in a VM. This is great, but it also means that when the OS runs out of memory, it starts paging the WSL 2 process, which slows it down significantly, which can cause scripts to time out. In practice, this means that I had to run start.sh a few times before everything came together.

> You can mitigate this drawback by closing memory-intensive applications (looking at you, Chrome). Also, if your machine has more than 16GB of RAM, you’ll probably be fine.
