### ISSUE TITLE
ksqlDB Websocket connection failes unless accessing localhost

### ISSUE THREAD

**Issue by theturtle32** [confluentinc/cp-demo#288]
If you run everything on your local machine and access it from your browser using `localhost` as the hostname, it works fine, as expected.

However, I have a separate beefy server machine that I use to run virtual machines, and I ran the example on an Ubuntu 20.04 VM and connected to Control Center from my laptop using the VM's IP address. I noticed that it was nonsensically trying to make a Websocket connection to localhost to get the results of ksqlDB queries, and so I went digging.

Turns out, it's hard-coded to use localhost in the `docker-compose.yml` file. Line 658-659 (at the time of this writing) contains:
```yaml
# Access ksqlDB server from a browser on your localhost
CONTROL_CENTER_KSQL_WIKIPEDIA_ADVERTISED_URL: http://localhost:8088
```

This really should be either dynamically resolved at runtime, or at the very least, this configuration variable should be called out in the quick start instructions.

**Comment by ybyzek** [comment]
@theturtle32 agree.  This will be improved by the current effort in https://github.com/confluentinc/cp-demo/pull/279 .  Feedback welcome in that PR, thank you.
