### ISSUE TITLE
ERROR: Service 'connect' failed to build: invalid reference format

### ISSUE THREAD

**Issue by dash7ou** [confluentinc/cp-demo#290]
Building connect
Step 1/12 : ARG CP_VERSION
Step 2/12 : FROM confluentinc/cp-server-connect-base:$CP_VERSION
ERROR: Service 'connect' failed to build: invalid reference format

image: localbuild/connect:${CONFLUENT_DOCKER_TAG}-${CONNECTOR_VERSION}
I can not know what is CONNECTOR_VERSION and I did not found it in .env file as REPOSITORY but I had added to REPOSITORY=confluentinc and its work fine and I had searched about localbuild/connect in hub.docker.com and not matches

**Comment by ybyzek** [comment]
@dash7ou `CONNECTOR_VERSION` is set in https://github.com/confluentinc/cp-demo/blob/6.0.0-post/scripts/start.sh#L15

**Comment by dash7ou** [comment]
@ybyzeb so how can i get it?
i had run 
1. make clean all to run Makefile files
2. docker-compose up -d

but CONNECTOR_VERSION missing
note: i am not expert with batch script :)

**Comment by dash7ou** [comment]
I have got CONNECTOR_VERSION from start.sh file and added 
CONNECTOR_VERSION=6.0.0-6.0.0
CP_VERSION=5.4.3 
to .env files

then run it and I had the same issue 
Step 1/12 : ARG CP_VERSION
Step 2/12 : FROM confluentinc/cp-server-connect-base:$CP_VERSION
ERROR: Service 'connect' failed to build: invalid reference format

**Comment by dash7ou** [comment]
I have solved it, by add values to Dockerfile-confluenthub
ARG CP_VERSION=6.0.0-6.0.0
ARG CONNECTOR_VERSION=5.4.3
