### ISSUE TITLE
start.sh stop at subject wikipedia.parsed-value (for topic wikipedia.parsed) to be registered in Schema Registry

### ISSUE THREAD

**Issue by qinxuan-chen** [confluentinc/cp-demo#338]
hi,

when i run ./scripts/start.sh, it stopped at below step in start.sh 

# Verify wikipedia.parsed topic is populated and schema is registered
MAX_WAIT=120
echo
echo -e "\nWaiting up to $MAX_WAIT seconds for subject wikipedia.parsed-value (for topic wikipedia.parsed) to be registered in Schema Registry"
retry $MAX_WAIT host_check_schema_registered || exit 1

Waiting up to 120 seconds for subject wikipedia.parsed-value (for topic wikipedia.parsed) to be registered in Schema Registry
........................ERROR: Failed after 120 seconds. Please troubleshoot and run again. For troubleshooting instructions see https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html#troubleshooting

please refer to attached for detail log.

my env is linux centos, jdk / docker version are sufficient for install.
[log.txt](https://github.com/confluentinc/cp-demo/files/5895899/log.txt)

thanks.
regards
qx

**Comment by ybyzek** [comment]
@qinxuan-chen can you please step through the troubleshooting steps in https://docs.confluent.io/platform/current/tutorials/cp-demo/docs/index.html#troubleshooting to check each point?

**Comment by qinxuan-chen** [comment]
thanks ybyzek,

found that it is due to url(https://raw.githubusercontent.com/wikimedia/mediawiki-event-schemas/master/jsonschema/mediawiki/recentchange/1.0.0.json) is no longer availible.

[2021-01-29 17:44:30,767] ERROR Failed to start task wikipedia-sse-0 (org.apache.kafka.connect.runtime.Worker)
org.apache.kafka.connect.errors.ConnectException: org.apache.kafka.common.config.ConfigException: Invalid value https://raw.githubusercontent.com/wikimedia/mediawiki-event-schemas/master/jsonschema/mediawiki/recentchange/1.0.0.json for configuration json.schema.url: exception while loading schema

is there any way to get it back and import manually?


thanks

**Comment by ybyzek** [comment]
@qinxuan-chen 

1. From my environment, https://raw.githubusercontent.com/wikimedia/mediawiki-event-schemas/master/jsonschema/mediawiki/recentchange/1.0.0.json is accessible.  Can you please confirm if there are networking/firewall issues blocking access to this in your environment?

2. That content is available at https://github.com/confluentinc/cp-demo/blob/6.0.1-post/scripts/connectors/media-wiki-RecentChange-event.reference.schema.json and you could modify the connector config to read this file locally.

**Comment by qinxuan-chen** [comment]
thank you @ybyzek , 

fyi, there is no networking/firewall blocking from my env, i try from hongkong server and china mainland server, both can not access githubusercontent.com(it prompt "raw.githubusercontent.com reject our connection request") & https://stream.wikimedia.org/v2/stream/recentchange ....

anyway i have managed to load json from local, but still got other issue. e.g. 
connect cluster:
[2021-01-29 21:31:53,231] INFO Starting EventSource client using URI: https://stream.wikimedia.org/v2/stream/recentchange (com.launchdarkly.eventsource.EventSource.)
[2021-01-29 21:36:53,563] ERROR Read timed out (com.github.cjmatta.kafka.connect.sse.ServerSentEventClient)

just realize there is no mention of SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL in docker-compose.yml for schemaregistry , is it normal? as i found other docker demo all need to mention this feature to connect schemaRegistry & zookeeper.

sorry for many questions..


thanks
qx

**Comment by ybyzek** [comment]
If your env cannot event reach https://stream.wikimedia.org/v2/stream/recentchange, then cp-demo won't work because there will be no source data.  For your consideration: explore other examples at https://developer.confluent.io/#kafka-tutorials-and-examples

Meanwhile, wrt `SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL ` please see this [blog post](SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL)

**Comment by qinxuan-chen** [comment]
understand ybyzek, but never mind i will make use of this demo setup and find another source.

after removing last part from start.sh (setup source/schema/consumer for wikimedia), setup is completed normally, but found that the connect cluster is not linked to c3, due to below reason:
[2021-01-30 22:22:49,848] WARN Error initializing InternalSecretConfigProvider (io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider:65)
io.confluent.kafka.secretregistry.exceptions.SecretRegistryInitializationException: Could not obtain master key

and i found that the host name for connect cluster is set as 199506b82402 (not connect) after start.sh completed

could you please advise?



thanks.

**Comment by qinxuan-chen** [comment]
do not why, after i rebuild connect & control center, it is solved...and previously ksqldb also not connect to c3, now it is okay also..

anyway, thanks ybyzek.

case closed.
