### ISSUE TITLE
cm_demo

### ISSUE THREAD

**Issue by Klaus-Lucas** [confluentinc/cp-demo#35]
Hello,

while installing cp_demo (a VM with 24GB RAM, CentOS 7) following these instructions
[https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html],
I've runned into 2 issues:

1) At  #2: In the advanced Docker preferences settings, increase the memory available to Docker to at least 8 GB (default is 2 GB).
I was not able to find this option. It would be helpful to have this command documented here.

2) At #3: Verify the status of the Docker containers.
I receive Exit 78 from eleastic_search and Exit 1 from kafka_client after a short time (see attached txt).
Don't know whats going wrong. I found no log files under /var/log.
Also attached the output from "docker-compose logs -f control-center".

Any help would be appreciated.

Klaus
[cp_demo.txt](https://github.com/confluentinc/cp-demo/files/1736774/cp_demo.txt)
[cc.txt](https://github.com/confluentinc/cp-demo/files/1736265/cc.txt)

**Comment by ybyzek** [comment]
Hi Klaus,

Documentation to increase Docker memory: https://docs.docker.com/docker-for-mac/#advanced

However, the logs you provided indicate 24GB memory allocated, which is more than enough.  You can crosscheck with the settings, but I don't think this is the issue.

Instead, I did a quick Google search and came across this article https://blog.wurbanski.me/posts/2017-04-16-get-elastic-with-elasticstack-and-docker-compose/ that addresses the issue where Elasticsearch "Exit 78".  Please see if that article resolves the Elasticsearch issue.

-Yeva

**Comment by Klaus-Lucas** [comment]
Dear Yeva,

I run the demo under Windows VMware Workstation containing a CentOS 7.
I understand now that the advanced settings are mentioned in conjunction with a Mac.

After setting "sysctl -w vm.max_map_count=262144" the exit code 78 was gone.
The only error I now have is:
"cpdemo_kafka-client_1     bash -c -a echo Waiting fo ...   Exit 1"

many thanks for your quick and very helpful comments.

:-) Klaus

**Comment by ybyzek** [comment]
Hi Klaus,

Have you been able to successfully run the demo and may we close this issue?

Thanks,
Yeva

**Comment by Klaus-Lucas** [comment]
Hello Yeva,

with your help I was able to run the demo.

☺ Klaus

Von: ybyzek [mailto:notifications@github.com]
Gesendet: Montag, 26. Februar 2018 02:27
An: confluentinc/cp-demo <cp-demo@noreply.github.com>
Cc: Lucas, Klaus <Klaus.Lucas@sva.de>; Author <author@noreply.github.com>
Betreff: Re: [confluentinc/cp-demo] cm_demo (#35)


Hi Klaus,

Have you been able to successfully run the demo and may we close this issue?

Thanks,
Yeva
