### ISSUE TITLE
CP-DEMO: unable to resolve docker endpoint: parse "tcp://Content-Type: application/json": invalid port ": application" after host

### ISSUE THREAD

**Issue by Elizabeth030483** [confluentinc/cp-demo#385]
Hello,
I used to run cp-demo successfully on my local mac. We are in the process of setting up Confluent Replicator. I want to see the cp-demo Replicator instance to see some basic (real time) flows. 

I have tried twice, using ./scripts/start.sh. I have enough memory for my docker instance (>8GB)

**Output:** Below shows the containers are running fine, but the 

Waiting up to 240 seconds for Connect to start
..✔ 

[+] Running 9/9
 ⠿ Container zookeeper       Running                                                                                                                                                0.0s
 ⠿ Container openldap        Running                                                                                                                                                0.0s
 ⠿ Container kafka2          Running                                                                                                                                                0.0s
 ⠿ Container kafka1          Running                                                                                                                                                0.0s
 ⠿ Container schemaregistry  Running                                                                                                                                                0.0s
 ⠿ Container restproxy       Started                                                                                                                                                2.2s
 ⠿ Container connect         Running                                                                                                                                                0.0s
 ⠿ Container ksqldb-server   Started                                                                                                                                                2.7s
 ⠿ Container ksqldb-cli      Started                                                                                                                                                3.9s
...

Start streaming from the Wikipedia SSE source connector:
unable to resolve docker endpoint: parse "tcp://Content-Type: application/json": invalid port ": application" after host

**Comment by ybyzek** [comment]
@Elizabeth030483 Based on output, seems like this part is failing: https://github.com/confluentinc/cp-demo/blob/6.2.0-post/scripts/connectors/submit_wikipedia_sse_config.sh. Please validate the `connect` container is running and check its logs for errors.

**Comment by brianstrauch** [comment]
I'm also running into this error. The `connect` container is still running, and there are no errors in its logs.

**Comment by brianstrauch** [comment]
https://github.com/docker/cli/issues/3277

**Comment by brianstrauch** [comment]
@Elizabeth030483 I was able to fix this issue by disabling "Use Docker Compose V2 release candidate" in the "Experimental Features" section of Docker Desktop (this was enabled by default in the latest Docker update).

**Comment by ybyzek** [comment]
@Elizabeth030483 thanks for reporting the issue, and @brianstrauch thanks for offering a quick workaround.

If the experimental version becomes the official version, this issue needs to be fixed (internal tracking jira: https://confluentinc.atlassian.net/browse/DEVX-2668)

**Comment by chuck-confluent** [comment]
I believe this weird docker compose v2 behavior has been addressed with:
- https://github.com/confluentinc/cp-demo/pull/418
- https://github.com/confluentinc/cp-demo/pull/421

Closing for now
