### ISSUE TITLE
Too many users in KafkaDevelopers LDAP Group

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-demo#393]
Here is where users are added to groups: https://github.com/confluentinc/cp-demo/blob/6.2.1-post/scripts/security/ldap_users/20_group_add.ldif

We need to use groups to showcase the power of RBAC. I would suggest two different groups, KafkaDevelopersA and KafkaDevelopersB, with alice and barnie in A and alice and charlie in B. This would make it possible to illustrate the benefits of RBAC a bit better. For example, alice would receive permissions associated with both groups.

I don't see any reason to add the rest of the users to the kafka developers group. Those are all confluent system users who don't need to be in group of developers.

**Comment by javabrett** [comment]
Could re-consider with a PR, otherwise no plans to do for now.
