### ISSUE TITLE
Docker Compose invalid due to syntax error

### ISSUE THREAD

**Issue by conan-goldsmith** [confluentinc/cp-demo#434]
The bootstrap.memory.lock and services.elasticsearch.environment.xpack.security.enabled are defined incorrectly, resulting in a docker-compose that is not runnable.
See error below:

```
ERROR: The Compose file './../docker-compose.yml' is invalid because:
services.elasticsearch.environment.xpack.security.enabled contains false, which is an invalid type, it should be a string, number, or a null
```
and 
```
ERROR: The Compose file './../docker-compose.yml' is invalid because:
services.elasticsearch.environment.xpack.security.enabled contains false, which is an invalid type, it should be a string, number, or a null
```

Blame line: https://github.com/confluentinc/cp-demo/blob/39b2cf43e625cda90bd3424dfe2157bae7c94b7c/docker-compose.yml#L641

**Comment by javabrett** [comment]
These environment keys/values have come and gone a couple of times from `docker-compose.yml` over time ... as things stand the values are _not_ in `master` or `7.5.2-post`, so this problem should not existing on current versions.  Closing - please re-open or re-log if these re-appear, or are a problem on specific older branches.
