### ISSUE TITLE
Infinite redirect in Kibana

### ISSUE THREAD

**Issue by jkorab** [confluentinc/cp-demo#53]
Running Ubuntu Xenial, with Chromium.

Attempting to access http://localhost:5601/app/kibana#/dashboard/Wikipedia results in a 302 redirect loop.

    This page isn’t working
    localhost redirected you too many times.
    Try clearing your cookies.
    ERR_TOO_MANY_REDIRECTS

Same thing in Firefox.

Could be related to this issue: https://discuss.elastic.co/t/kibana-5-w-x-pack-stuck-in-redirect-loop-on-login/66550/3

**Comment by ybyzek** [comment]
@JimGalasyn also reported an issue accessing the Kibana dashboard running Ubuntu 18.04 with Chromium.  @JimGalasyn -- did you have a resolution to the issue?  

`cp-demo` is verified only on macOS, so any help from you and the community on how to resolve this Ubuntu-related issue would be much appreciated.

**Comment by isaacmcn** [comment]
I'm getting the same thing and I wonder if it is to do with elasticsearch not running correctly.

```
sudo docker-compose ps 

     Name                   Command                State                              Ports
----------------------------------------------------------------------------------------------------------------------
connect          /etc/confluent/docker/run        Up        0.0.0.0:8083->8083/tcp, 9092/tcp
control-center   /etc/confluent/docker/run        Up        0.0.0.0:9021->9021/tcp
elasticsearch    /bin/bash bin/es-docker          Exit 78
kafka-client     bash -c -a echo Waiting fo ...   Exit 0
kafka1           /etc/confluent/docker/run        Up        0.0.0.0:29091->29091/tcp, 0.0.0.0:9091->9091/tcp, 9092/tcp
kafka2           /etc/confluent/docker/run        Up        0.0.0.0:29092->29092/tcp, 0.0.0.0:9092->9092/tcp
kibana           /bin/sh -c /usr/local/bin/ ...   Up        0.0.0.0:5601->5601/tcp
ksql-cli         perl -e while(1){ sleep 99 ...   Up        0.0.0.0:8088->8088/tcp
replicator       tail -f /dev/null                Up        8083/tcp, 9092/tcp
restproxy        /etc/confluent/docker/run        Up        8082/tcp, 0.0.0.0:8086->8086/tcp
schemaregistry   /etc/confluent/docker/run        Up        8081/tcp, 0.0.0.0:8085->8085/tcp
zookeeper        /etc/confluent/docker/run        Up        0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp
```

So elasticsearch looks like it has stopped.

In the logs:

```
 sudo docker-compose logs elasticsearch

<snip>
elasticsearch     | [2018-07-05T05:48:40,004][INFO ][o.e.b.BootstrapChecks    ] [yjhoWmY] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elasticsearch     | ERROR: [1] bootstrap checks failed
elasticsearch     | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch     | [2018-07-05T05:48:40,029][INFO ][o.e.n.Node               ] [yjhoWmY] stopping ...
elasticsearch     | [2018-07-05T05:48:40,284][INFO ][o.e.n.Node               ] [yjhoWmY] stopped
elasticsearch     | [2018-07-05T05:48:40,284][INFO ][o.e.n.Node               ] [yjhoWmY] closing ...
elasticsearch     | [2018-07-05T05:48:40,748][INFO ][o.e.n.Node               ] [yjhoWmY] closed
```

**Comment by rpozarickij** [comment]
I experienced the same issue on Ubuntu 18.04.

[This](https://github.com/docker-library/elasticsearch/issues/111#issuecomment-268989731) solved the issue for me.

**Comment by ybyzek** [comment]
@rpozarickij thanks for the suggestion!

@JimGalasyn would you be able to validate whether the tip provided by @rpozarickij works in your environment?

**Comment by JimGalasyn** [comment]
@ybyzek, will do!

**Comment by JimGalasyn** [comment]
@ybyzek Verified that it works end-to-end with CP 5.2.1 on Ubuntu 18.04.

**Comment by ybyzek** [comment]
Thanks for the confirmation @JimGalasyn !
