### ISSUE TITLE
Demo video seems entirely wrong

### ISSUE THREAD

**Issue by EricGregMiller** [confluentinc/cp-demo#54]
In the demo video git clone --recursive is used to clone this repository. It shows sub-modules being installed. Then in the cp-demo folder "make clean all" is executed. My experience disagrees completely with this.

1. When I clone I see no sub-modules.
2. There is no Makefile in the cp-demo folder.

**Comment by ybyzek** [comment]
@EricGregMiller : it is no longer required to git clone using `--recursive` nor to compile using `make`.  Please disregard the video that refers to those steps.

The steps required have been updated to the text described in the [documentation](https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html#run-demo).
