### ISSUE TITLE
Huge ass time icons

### ISSUE THREAD

**Issue by TeNNoX** [confluentinc/cp-demo#62]
I cloned this repo (529e469c3aa8f4ad9f75f64685271f629995b9b4), ran `./scripts/start.sh`, opened the control center, and look what I was greeted by:

![Screenshot](https://screenshotscdn.firefoxusercontent.com/images/e425e799-d1a4-477f-b116-efb34900222c.png)

![Time picker](https://screenshotscdn.firefoxusercontent.com/images/99c0f5f5-fcfc-430e-ac76-aa8ebb355a4e.png)

The `<svg>` element has `width="1.3rem"` and `height="1.3rem"` attributes, but they don't work with relative values in some browsers (in my case firefox - but chrome works):
The issue is described in more detail here:
https://wiki.mozilla.org/SVG:Sizing

I did not find a repository for the control center itself, that's why I'm posting it here.

**Comment by ybyzek** [comment]
Hi @TeNNoX , Control Center is currently supported just on Google Chrome, as documented here: https://docs.confluent.io/current/control-center/docs/installation/install-apache-kafka.html
