### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by jeffrey-d-lipkowitz** [confluentinc/cp-demo#99]
I started the demo on mac os machine with 4gb for ram, docker and ,JB.

I got the following error.
ERROR: The logs in control-center container do not show 'Started NetworkTrafficServerConnector' after 300 seconds. Please troubleshoot with 'docker-compose ps' and 'docker-compose logs'.

This is assuming a fresh instal and the user had selected the start.sh command

**Comment by jeffrey-d-lipkowitz** [comment]
when i run the command ./start.sh

The following warning is also displayed.

Removing network cp-demo_default
WARNING: Network cp-demo_default not found.
Generate keys and certificates used for SSL
Generating a 2048 bit RSA private key

**Comment by jeffrey-d-lipkowitz** [comment]
]
[Kafka1logs.txt](https://github.com/confluentinc/cp-demo/files/3113815/Kafka1logs.txt)
[logs.txt](https://github.com/confluentinc/cp-demo/files/3113816/logs.txt)

**Comment by jeffrey-d-lipkowitz** [comment]
Reference to a previous issue with similar error. It's open :(

https://github.com/confluentinc/cp-docker-images/issues/662

**Comment by pogzie** [comment]
have you tried increasing the max_wait value? https://github.com/confluentinc/cp-demo/blob/6b12de738697eb01920ac4e18fd5946adfa41a9c/scripts/start.sh#L40 

it might just take longer to load

**Comment by javabrett** [comment]
Closing stale issue - please open a new issue if this problem re-occurs.
